#!/bin/bash

# fix-partitions --- Fix partition before and after APT invocation
# Copyright © 2014 Sébastien Gross <seb•ɑƬ•chezwam•ɖɵʈ•org>
# Last changed: 2014-04-03 14:51:19

# This program is free software. It comes without any warranty, to
# the extent permitted by applicable law. You can redistribute it
# and/or modify it under the terms of the Do What The Fuck You Want
# To Public License, Version 2, as published by Sam Hocevar. See
# http://sam.zoy.org/wtfpl/COPYING for more details.


PATHS="/tmp /usr"
me=$(basename $0)

function before_install()  {
    for p in $PATHS; do
	mount | grep -F " on $p " -q
	if test $? -eq 1; then
	    continue
	fi
        mount -o remount,rw,exec $p
    done
}

function after_install() {
    for p in $PATHS; do
	opts=$(awk "{if(\$2==\"$p\"){print \$4}}" /etc/fstab)
	if test -n "$opts"; then
	    mount -o remount,$opts $p
	    # killall getty || true
	fi
    done
}

case $me in
    fix-partitions-before-apt) before_install;;
    fix-partitions-after-apt) after_install;;
    *)
	case $1 in
	    before) before_install;;
	    after) after_install;;
	    *) echo "Could not do anything" ;;
	esac
	;;
esac
